IMS.WEB/Controllers/BrandController.cs
using IMS.CustomException;
using IMS.Entity.EntityViewModels;
using IMS.Service;
using log4net;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace IMS.WEB.Controllers
{
    public class BrandController : Controller
    {

        private readonly IBrandService _brandService;
        //private readonly ApplicationUserManager _applicationUserManager;
        private static readonly ILog _logger = LogManager.GetLogger(typeof(BrandController));
        //private static readonly ILog _logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        public BrandController()
        {
            _brandService = new BrandService();
            //_applicationUserManager = new ApplicationUserManager(new CustomUserStore(new ApplicationDbContext()));
        }

        public ActionResult CreateBrand()
        {
            return View(new BrandViewModel());
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> CreateBrand(BrandViewModel brand)
        {
            string message = string.Empty;
            bool isValid = false;

            try
            {
                if (brand != null)
                {
                    brand.CreatedBy = User.Identity.Name;
                    brand.ModifyBy = User.Identity.Name;
                    await _brandService.CreateBrandService(brand);
                    isValid = true;
                    message = "Brand is added successfully!";
                }
                else
                {
                    message = "Something is wrong! Please try again!";
                }

            }
            catch (DuplicateValueException ex)
            {
                message = ex.Message;
            }
            catch (InvalidNameException ex)
            {
                message = ex.Message;
            }
            catch (Exception ex)
            {
                _logger.Error(message, ex);
                message = "Something went wrong!";
            }

            return Json(new
            {
                Message = message,
                IsValid = isValid
            }, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public ActionResult Load()
        {
            return View();
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult> LoadBrandData()
        {
            var brandViewModelList = new List<BrandViewModel>();
            try
            {

                var brand = await _brandService.GetAll();

                //foreach (var item in brand)
                //{
                //    new BrandViewModel
                //    {
                //        Id = item.Id,
                //        BrandName = item.BrandName,
                //        CreatedDate = DateTime.Now,
                //        ModifyBy = item.ModifyBy,
                //    };
                //}
                brandViewModelList = brand.Select(b => new BrandViewModel
                {
                    Id = b.Id,
                    BrandName = b.BrandName,
                    CreatedDate = b.CreatedDate,
                    ModifyDate = b.ModifyDate
                }).ToList();

            }
            catch (Exception ex)
            {
                _logger.Error(ex.Message, ex);
            }

            return Json(new
            {
                recordsTotal = brandViewModelList.Count,
                recordsFiltered = brandViewModelList.Count,
                data = brandViewModelList,
            }, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult> BrandDetails(long id)
        {
            bool isSuccess = false;
            string message = string.Empty;
            var brandDetails = new BrandViewModel();

            try
            {
                brandDetails = await _brandService.BrandDetailsService(id);

                if (brandDetails != null)
                {
                    isSuccess = true;
                }
                else
                {
                    message = "Brand not found!";
                }
            }
            catch (Exception ex)
            {
                message = "Something went wrong!";
                _logger.Error(ex.Message, ex);
            }

            return Json(new
            {
                Details = new
                {
                    brandDetails.CreatedBy,
                    CreatedDate = brandDetails.CreatedDate?.ToString("yyyy-MM-dd HH:mm:ss tt"),
                    brandDetails.ModifyBy,
                    ModifyDate = brandDetails.ModifyDate?.ToString("yyyy-MM-dd HH:mm:ss tt")
                },
                IsSuccess = isSuccess,
                Message = message,
            }, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult> Update(long id)
        {
            bool isSuccess = false;
            string message = string.Empty;
            var updateBrand = new BrandViewModel();

            try
            {
                updateBrand = await _brandService.GetById(id);

                if (updateBrand == null)
                {
                    message = "Brand is not found!";
                }
                else
                {
                    isSuccess = true;
                }
            }
            catch (Exception ex)
            {
                _logger.Error(ex.Message, ex);
                message = "Something went wrong!";
            }

            return Json(new
            {
                UpdateBrandData = updateBrand,
                IsSuccess = isSuccess,
                Message = message,
            }, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> Update(long id, BrandViewModel brand)
        {
            string message = string.Empty;
            bool isSuccess = false;

            if (brand == null)
            {
                message = "Brand is not found! Try again";
            }
            else
            {
                try
                {
                    //brand.ModifyBy = long.Parse(User.Identity.GetUserId());
                    brand.ModifyBy = User.Identity.Name;
                    await _brandService.Update(brand.Id, brand);
                    isSuccess = true;
                    message = "Brand is updated successfully!";
                }
                catch (DuplicateValueException ex)
                {
                    message = ex.Message;
                }
                catch (InvalidNameException ex)
                {
                    message = ex.Message;
                }
                catch (Exception ex)
                {
                    _logger.Error(message, ex);
                    message = "Something went wrong!";
                }
            }

            return Json(new
            {
                IsSuccess = isSuccess,
                Message = message,
            });
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> Delete(long id)
        {
            string message = string.Empty;
            bool isSuccess = false;

            try
            {
                var brand = await _brandService.GetById(id);

                if (brand.Id != 0)
                {
                    await _brandService.DeleteAsync(id);
                    message = "Brand is deleted successfully!";
                    isSuccess = true;
                }
                else
                {
                    message = "Brand is not found!";
                }
            }
            catch (Exception ex)
            {
                _logger.Error(message, ex);
                message = "Something went wrong!";
            }

            return Json(new
            {
                Message = message,
                IsSuccess = isSuccess
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

IMS.WEB/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IMS.WEB.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult LoadAll()
        {
            return View();
        }
    }
}

IMS.WEB/Controllers/SkuController.cs
using IMS.CustomException;
using IMS.Entity.Entities;
using IMS.Entity.EntityViewModels;
using IMS.Service;
using log4net;
using System;
using System.Collections.Generic;
using System.Drawing.Drawing2D;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using IMS.Entity.EntityViewModels.SKUViewModel;

namespace IMS.WEB.Controllers
{
    public class SkuController : Controller
    {
        private readonly ISkuService _skuService;
        public static readonly ILog _logger = LogManager.GetLogger(typeof(SkuController));
        public SkuController()
        {
            _skuService = new SkuService();
        }

        [Authorize]
        public ActionResult CreateSKU()
        {
            return View(new SkuViewModel());
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> CreateSKU(SkuCreateViewModel skuCreateViewModel)

        {
            string message = string.Empty;
            bool isValid = false;

            try
            {
                if (skuCreateViewModel != null)
                {
                    skuCreateViewModel.CreatedBy = User.Identity.Name;
                    skuCreateViewModel.ModifyBy = User.Identity.Name;
                    await _skuService.CreateSkuService(skuCreateViewModel);
                    isValid = true;
                    message = "SKU is added successfully!";
                }
                else
                {
                    message = "Something is wrong! Please try again!";
                }
            }
            catch (DuplicateValueException ex)
            {
                message = ex.Message;
            }
            catch (InvalidNameException ex)
            {
                message = ex.Message;
            }
            catch (Exception ex)
            {
                _logger.Error(message, ex);
                message = "Something went wrong!";
            }

            return Json(new
            {
                Message = message,
                IsValid = isValid
            }, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Load()
        {
            return View();
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult> LoadSkuData()
        {
            var skuViewModelList = new List<SkuViewModel>();

            try
            {
                var sku = await _skuService.GetAll();

                skuViewModelList = sku.Select(b => new SkuViewModel
                {
                    Id = b.Id,
                    SKUsName = b.SKUsName,
                    CreatedDate = b.CreatedDate,
                    ModifyDate = b.ModifyDate
                }).ToList();
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
            }

            return Json(new
            {
                recordsTotal = skuViewModelList.Count,
                recordsFiltered = skuViewModelList.Count,
                data = skuViewModelList,
            },
            JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult> SkuDetails(long id)
        {
            bool isSuccess = false;
            string message = string.Empty;
            var skuDetails = new SkuViewModel();

            try
            {
                skuDetails = await _skuService.SkuDetailsService(id);

                if (skuDetails != null)
                {
                    isSuccess = true;
                }
                else
                {
                    message = "SKU not found!";
                }
            }
            catch (Exception ex)
            {
                message = "Something went wrong!";
                _logger.Error(ex.Message);
            }

            return Json(new
            {
                Details = new
                {
                    skuDetails.CreatedBy,
                    CreatedDate = skuDetails.CreatedDate?.ToString("yyyy-MM-dd HH:mm:ss tt"),
                    skuDetails.ModifyBy,
                    ModifyDate = skuDetails.ModifyDate?.ToString("yyyy-MM-dd HH:mm:ss tt")
                },
                IsSuccess = isSuccess,
                Message = message,
            }, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult> Update(long id)
        {
            bool isSuccess = false;
            string message = string.Empty;
            var sku = new SkuViewModel();

            try
            {
                sku = await _skuService.GetById(id);

                if (sku == null)
                {
                    message = "SKU is not found!";
                }
                else
                {
                    isSuccess = true;
                }
            }
            catch (Exception ex)
            {
                _logger.Error(message, ex);
                message = "Something went wrong!";
            }

            return Json(new
            {
                UpdateSkuData = sku,
                IsSuccess = isSuccess,
                Message = message,
            }, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> Update(long id, SkuUpdateViewModel skuUpdateViewModel)
        {
            string message = string.Empty;
            bool isSuccess = false;

            if (skuUpdateViewModel == null)
            {
                message = "SKU is not found! Try again";
            }
            else
            {
                try
                {
                    //brand.ModifyBy = long.Parse(User.Identity.GetUserId());
                    skuUpdateViewModel.ModifyBy = User.Identity.Name;
                    await _skuService.UpdateAsync(id, skuUpdateViewModel);
                    isSuccess = true;
                    message = "SKU is updated successfully!";
                }
                catch (InvalidNameException ex)
                {
                    message = ex.Message;
                }
                catch (DuplicateValueException ex)
                {
                    message = ex.Message;
                }
                catch (Exception ex)
                {
                    _logger.Error(message, ex);
                    message = "Something went wrong!";
                }
            }

            return Json(new
            {
                IsSuccess = isSuccess,
                Message = message,
            });
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> Delete(long id)
        {
            string message = string.Empty;
            bool isSuccess = false;
            var sku = new SkuViewModel();

            try
            {
                sku = await _skuService.GetById(id);

                if (sku != null)
                {
                    await _skuService.DeleteAsync(id);
                    message = "SKU is deleted successfully!";
                    isSuccess = true;
                }
                else
                {
                    message = "SKU is not found!";
                }
            }
            catch (Exception ex)
            {
                _logger.Error(message, ex);
                message = "Something went wrong!";
            }


            return Json(new
            {
                Message = message,
                IsSuccess = isSuccess
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

IMS.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Inventory Management System</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)
    <link href="~/CustomStyle/Style.css" type="text/css" rel="stylesheet" />
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/5.2.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-e6a226f2a0896f90bc78006d2b2b6a1d2f3f3f35b1d6f76b1c64de0173545f1b" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("IMS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Product Management", "LoadAll", "Product", new { area = "" }, new { @class = "nav-link" })</li>
                    @*<li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Product Management
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Customer Management
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Supplier Management
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>*@
                    <li>@Html.ActionLink("Brands", "Load", "Brand", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Category", "LoadAll", "Category", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("ProductTypes", "LoadAll", "ProductType", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("ProductSKU", "Load", "Sku", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Customer Management", "Load", "Customer", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Supplier Management", "Load", "Supplier", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Inventory Management System</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/5.2.3/js/bootstrap.bundle.min.js" integrity="sha384-DFt9YcmF7Ek6Flc7p2UCBVF0A6+J/Up/pGrF2Rvi5fPZjU9ZV7YqxS7oCG2GkU2T" crossorigin="anonymous"></script>
</body>
</html>